using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Operations;

namespace Surefire.SourceGeneration;

/// <summary>
///     Incremental source generator that intercepts Surefire registration call sites and rewrites
///     them into AOT-safe calls to descriptor-taking overloads. Modeled on ASP.NET Core's Request
///     Delegate Generator: the user keeps writing <c>app.AddJob("Name", handler)</c> and
///     <c>.OnSuccess(handler)</c> verbatim; the generator emits per-call-site interceptor methods
///     and descriptor factories so no reflection runs at registration time.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class SurefireGenerator : IIncrementalGenerator
{
    private const string GeneratedNamespace = "Surefire.Generated";
    private const string SurefireOptionName = "build_property.SurefireSourceGenerationEnabled";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var enabled = context.AnalyzerConfigOptionsProvider.Select(static (opts, _) =>
            !opts.GlobalOptions.TryGetValue(SurefireOptionName, out var value)
            || string.Equals(value, "true", StringComparison.OrdinalIgnoreCase));

        var addJobCalls = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => IsCandidateAddJobInvocation(node),
                static (ctx, ct) => TryExtractAddJobCall(ctx, ct))
            .Where(static c => c is { })
            .Select(static (c, _) => c!);

        var callbackCalls = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => IsCandidateCallbackInvocation(node),
                static (ctx, ct) => TryExtractCallbackCall(ctx, ct))
            .Where(static c => c is { })
            .Select(static (c, _) => c!);

        var clientCalls = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => IsCandidateIJobClientInvocation(node),
                static (ctx, ct) => TryExtractIJobClientCall(ctx, ct))
            .Where(static c => c is { })
            .Select(static (c, _) => c!);

        // Check whether the consuming compilation already has access to
        // `System.Runtime.CompilerServices.InterceptsLocationAttribute` from a referenced
        // assembly. If so, the polyfill must not be emitted (it would conflict).
        var hasInterceptsLocationAttribute = context.CompilationProvider.Select(static (compilation, _) =>
            compilation.GetTypesByMetadataName("System.Runtime.CompilerServices.InterceptsLocationAttribute")
                .Any(t => t.DeclaredAccessibility == Accessibility.Public
                          || t.DeclaredAccessibility == Accessibility.Internal));

        var combined = addJobCalls.Collect()
            .Combine(callbackCalls.Collect())
            .Combine(clientCalls.Collect())
            .Combine(hasInterceptsLocationAttribute)
            .Combine(enabled);
        context.RegisterSourceOutput(combined, static (ctx, data) =>
        {
            var ((((addJobs, callbacks), clients), hasAttr), isEnabled) = data;
            if (!isEnabled)
            {
                return;
            }

            if (addJobs.IsDefaultOrEmpty && callbacks.IsDefaultOrEmpty && clients.IsDefaultOrEmpty)
            {
                return;
            }

            if (!hasAttr)
            {
                EmitInterceptsLocationPolyfill(ctx);
            }

            EmitInterceptors(ctx, addJobs, callbacks, clients);
        });
    }

    private static void EmitInterceptsLocationPolyfill(SourceProductionContext context)
    {
        // Emit a local polyfill only when the compilation does not reference InterceptsLocationAttribute.
        const string source = """
                              // <auto-generated/>
                              #nullable enable
                              #pragma warning disable CS9113

                              namespace System.Runtime.CompilerServices
                              {
                                  [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]
                                  internal sealed class InterceptsLocationAttribute : global::System.Attribute
                                  {
                                      public InterceptsLocationAttribute(int version, string data) { }
                                  }
                              }

                              """;
        context.AddSource("InterceptsLocationAttribute.g.cs", source);
    }

    private static bool IsCandidateAddJobInvocation(SyntaxNode node) =>
        node is InvocationExpressionSyntax invocation
        && invocation.ArgumentList.Arguments.Count == 2
        && GetInvokedMemberName(invocation) == "AddJob";

    private static bool IsCandidateCallbackInvocation(SyntaxNode node) =>
        node is InvocationExpressionSyntax invocation
        && invocation.ArgumentList.Arguments.Count == 1
        && GetInvokedMemberName(invocation) is "OnSuccess" or "OnRetry" or "OnDeadLetter";

    private static bool IsCandidateIJobClientInvocation(SyntaxNode node) =>
        node is InvocationExpressionSyntax invocation
        && GetInvokedMemberName(invocation) is { } name
        && IJobClientCallInspector.IsCandidate(name);

    private static string? GetInvokedMemberName(InvocationExpressionSyntax invocation) => invocation.Expression switch
    {
        MemberAccessExpressionSyntax m => m.Name.Identifier.ValueText,
        MemberBindingExpressionSyntax m => m.Name.Identifier.ValueText, // null-conditional: host?.AddJob(...)
        _ => null
    };

    private static IJobClientCall? TryExtractIJobClientCall(GeneratorSyntaxContext context,
        CancellationToken cancellationToken)
    {
        var invocation = (InvocationExpressionSyntax)context.Node;
        var symbol = context.SemanticModel.GetSymbolInfo(invocation, cancellationToken).Symbol as IMethodSymbol;
        if (symbol is null)
        {
            return null;
        }

        return IJobClientCallInspector.Inspect(invocation, context.SemanticModel, symbol, cancellationToken);
    }

    private static AddJobCall? TryExtractAddJobCall(GeneratorSyntaxContext context, CancellationToken cancellationToken)
    {
        var invocation = (InvocationExpressionSyntax)context.Node;
        var symbol = context.SemanticModel.GetSymbolInfo(invocation, cancellationToken).Symbol as IMethodSymbol;
        if (symbol is null
            || symbol.Name != "AddJob"
            || symbol.ContainingType?.ToDisplayString() != "Microsoft.Extensions.Hosting.HostExtensions"
            || symbol.TypeArguments.Length != 1)
        {
            return null;
        }

        var arguments = invocation.ArgumentList.Arguments;
        var handlerExpression = arguments[1].Expression;
        var handlerSymbol = GetHandlerMethodSymbol(context.SemanticModel, handlerExpression, cancellationToken);
        if (handlerSymbol is null)
        {
            return null;
        }

        var location = context.SemanticModel.GetInterceptableLocation(invocation, cancellationToken);
        if (location is null)
        {
            return null;
        }

        var handlerInfo = HandlerSignatureInspector.Inspect(handlerSymbol);
        if (handlerInfo is null)
        {
            // The handler can't be statically analyzed (anonymous types, inaccessible parameter
            // types, etc.). Skip interception; the call falls through to the
            // [RequiresUnreferencedCode]-annotated AddJob<TDelegate> overload, which produces
            // the standard IL2026/IL3050 warning under AOT.
            return null;
        }

        return new(
            location.GetInterceptsLocationAttributeSyntax(),
            handlerInfo,
            TryCaptureSourceCode(invocation, handlerExpression, handlerSymbol, cancellationToken));
    }

    private static string TryCaptureSourceCode(InvocationExpressionSyntax addJobInvocation,
        ExpressionSyntax handlerExpression,
        IMethodSymbol handlerSymbol,
        CancellationToken cancellationToken)
    {
        var registrationSource = TryCaptureRegistrationSourceCode(addJobInvocation);
        var handlerSource = handlerExpression is AnonymousFunctionExpressionSyntax
            ? null
            : TryCaptureHandlerSourceCode(handlerSymbol, cancellationToken);

        return handlerSource is { Length: > 0 }
            ? registrationSource + "\n\n" + handlerSource
            : registrationSource;
    }

    private static string? TryCaptureHandlerSourceCode(IMethodSymbol handlerSymbol, CancellationToken cancellationToken)
    {
        foreach (var syntaxReference in handlerSymbol.DeclaringSyntaxReferences)
        {
            var syntax = syntaxReference.GetSyntax(cancellationToken);
            switch (syntax)
            {
                case MethodDeclarationSyntax { Body: not null } method:
                    return TrimSource(method);
                case MethodDeclarationSyntax { ExpressionBody: not null } method:
                    return TrimSource(method);
                case LocalFunctionStatementSyntax { Body: not null } local:
                    return TrimSource(local);
                case LocalFunctionStatementSyntax { ExpressionBody: not null } local:
                    return TrimSource(local);
                case AnonymousFunctionExpressionSyntax anonymous:
                    return TrimSource(anonymous);
            }
        }

        return null;
    }

    private static string TrimSource(SyntaxNode node) => node.ToFullString().Trim();

    private static string TryCaptureRegistrationSourceCode(InvocationExpressionSyntax addJobInvocation)
    {
        SyntaxNode current = addJobInvocation;
        while (current.Parent is MemberAccessExpressionSyntax { Expression: { } expression } memberAccess
               && ReferenceEquals(expression, current)
               && memberAccess.Parent is InvocationExpressionSyntax chainedInvocation)
        {
            current = chainedInvocation;
        }

        return TrimSource(current);
    }

    private static CallbackCall? TryExtractCallbackCall(GeneratorSyntaxContext context,
        CancellationToken cancellationToken)
    {
        var invocation = (InvocationExpressionSyntax)context.Node;
        var symbol = context.SemanticModel.GetSymbolInfo(invocation, cancellationToken).Symbol as IMethodSymbol;
        if (symbol is null)
        {
            return null;
        }

        var kind = symbol.Name switch
        {
            "OnSuccess" => CallbackKind.OnSuccess,
            "OnRetry" => CallbackKind.OnRetry,
            "OnDeadLetter" => CallbackKind.OnDeadLetter,
            _ => (CallbackKind?)null
        };
        if (kind is null)
        {
            return null;
        }

        // Match the Delegate-taking overloads on JobBuilder and SurefireOptions. The
        // CallbackDescriptor-taking overloads must not be re-intercepted.
        var containingType = symbol.ContainingType?.ToDisplayString();
        var target = containingType switch
        {
            "Surefire.JobBuilder" => CallbackTarget.JobBuilder,
            "Surefire.SurefireOptions" => CallbackTarget.SurefireOptions,
            _ => (CallbackTarget?)null
        };
        if (target is null)
        {
            return null;
        }

        // Only the Delegate-taking overload needs interception; the CallbackDescriptor overload
        // is already AOT-safe by construction.
        if (symbol.Parameters.Length != 1
            || symbol.Parameters[0].Type.ToDisplayString() != "System.Delegate")
        {
            return null;
        }

        var handlerExpression = invocation.ArgumentList.Arguments[0].Expression;
        var handlerSymbol = GetHandlerMethodSymbol(context.SemanticModel, handlerExpression, cancellationToken);
        if (handlerSymbol is null)
        {
            return null;
        }

        var location = context.SemanticModel.GetInterceptableLocation(invocation, cancellationToken);
        if (location is null)
        {
            return null;
        }

        var handlerInfo = HandlerSignatureInspector.Inspect(handlerSymbol);
        if (handlerInfo is null)
        {
            // Falls through to the [RequiresUnreferencedCode]-annotated On*(Delegate) overload.
            return null;
        }

        return new(location.GetInterceptsLocationAttributeSyntax(), handlerInfo, target.Value, kind.Value);
    }

    [SuppressMessage("Trimming", "RS1041",
        Justification = "Generator runs in the host build, not consumed at run time.")]
    private static IMethodSymbol? GetHandlerMethodSymbol(SemanticModel model, ExpressionSyntax expression,
        CancellationToken cancellationToken)
    {
        var info = model.GetSymbolInfo(expression, cancellationToken);
        if (info.Symbol is IMethodSymbol method)
        {
            return method;
        }

        if (expression is AnonymousFunctionExpressionSyntax)
        {
            var op = model.GetOperation(expression, cancellationToken);
            if (op is IAnonymousFunctionOperation anon)
            {
                return anon.Symbol;
            }
        }

        return null;
    }

    private static void EmitInterceptors(SourceProductionContext context,
        ImmutableArray<AddJobCall> addJobs,
        ImmutableArray<CallbackCall> callbacks,
        ImmutableArray<IJobClientCall> clientCalls)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS9258, CS9113, CS8604");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine("using System.Text.Json.Serialization.Metadata;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Microsoft.Extensions.Hosting;");
        sb.AppendLine("using Surefire;");
        sb.AppendLine();
        sb.AppendLine($"namespace {GeneratedNamespace};");
        sb.AppendLine();
        // Generated interceptors call Delegate.CreateDelegate with a MethodInfo captured from the
        // user's call site. The original method-group reference roots the target, so the trimmer
        // can't drop it - but the linker analyzer can't see that, so suppress IL2026/IL3050 here.
        sb.AppendLine(
            "[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage(\"Trimming\", \"IL2026\", Justification = \"Target method is rooted by the original call site.\")]");
        sb.AppendLine(
            "[global::System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage(\"AOT\", \"IL3050\", Justification = \"Closed-generic dispatch only; no runtime codegen.\")]");
        sb.AppendLine("file static class SurefireInterceptors");
        sb.AppendLine("{");

        EmitAddJobInterceptors(sb, addJobs);
        EmitCallbackInterceptors(sb, callbacks);
        IJobClientEmitter.EmitInterceptors(sb, clientCalls);
        if (!clientCalls.IsDefaultOrEmpty && clientCalls.Any(c => c.ArgsShape == ArgsExpressionShape.Anonymous))
        {
            IJobClientEmitter.EmitAnonHelper(sb);
        }

        sb.AppendLine("}");

        context.AddSource("SurefireInterceptors.g.cs", sb.ToString());
    }

    private static void EmitAddJobInterceptors(StringBuilder sb, ImmutableArray<AddJobCall> calls)
    {
        if (calls.IsDefaultOrEmpty)
        {
            return;
        }

        for (var i = 0; i < calls.Length; i++)
        {
            var call = calls[i];
            var handler = call.Handler;
            var delegateType = handler.RenderDelegateType();

            // The interceptor must match the original AddJob<TDelegate> generic signature
            // verbatim. Lambdas with optional parameters get compiler-synthesized delegate types
            // that aren't assignable to Func<...> by name, so the interceptor accepts TDelegate
            // generically and re-binds the handler's MethodInfo to the canonical Func/Action via
            // Delegate.CreateDelegate (AOT-safe, no reflection emit).
            sb.Append("    ").AppendLine(call.InterceptsLocationAttribute);
            sb.AppendLine(
                $"    internal static Surefire.JobBuilder AddJob_{i}<TDelegate>(this IHost host, string name, TDelegate handler)");
            sb.AppendLine("        where TDelegate : System.Delegate");
            sb.AppendLine("    {");
            sb.AppendLine(
                $"        var normalized = ({delegateType})System.Delegate.CreateDelegate(typeof({delegateType}), handler.Target, handler.Method);");
            sb.AppendLine(
                $"        return Microsoft.Extensions.Hosting.HostExtensions.AddJob(host, BuildDescriptor_{i}(name, normalized));");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine(
                $"    private static Surefire.JobRegistrationDescriptor BuildDescriptor_{i}(string name, {delegateType} handler)");
            sb.AppendLine("    {");
            DescriptorEmitter.EmitDescriptorBody(sb, i, handler, call.SourceCode);
            sb.AppendLine("    }");
            sb.AppendLine();
        }
    }

    private static void EmitCallbackInterceptors(StringBuilder sb, ImmutableArray<CallbackCall> calls)
    {
        if (calls.IsDefaultOrEmpty)
        {
            return;
        }

        for (var i = 0; i < calls.Length; i++)
        {
            var call = calls[i];
            var handler = call.Handler;
            var delegateType = handler.RenderDelegateType();
            var receiverType = call.Target switch
            {
                CallbackTarget.JobBuilder => "Surefire.JobBuilder",
                CallbackTarget.SurefireOptions => "Surefire.SurefireOptions",
                _ => throw new InvalidOperationException("Unknown callback target.")
            };
            var methodName = call.Kind switch
            {
                CallbackKind.OnSuccess => "OnSuccess",
                CallbackKind.OnRetry => "OnRetry",
                CallbackKind.OnDeadLetter => "OnDeadLetter",
                _ => throw new InvalidOperationException("Unknown callback kind.")
            };

            sb.Append("    ").AppendLine(call.InterceptsLocationAttribute);
            sb.AppendLine(
                $"    internal static {receiverType} {methodName}_Cb_{i}(this {receiverType} receiver, System.Delegate callback)");
            sb.AppendLine("    {");
            sb.AppendLine(
                $"        var normalized = ({delegateType})System.Delegate.CreateDelegate(typeof({delegateType}), callback.Target, callback.Method);");
            sb.AppendLine($"        return receiver.{methodName}(BuildCallbackDescriptor_{i}(normalized));");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine(
                $"    private static Surefire.CallbackDescriptor BuildCallbackDescriptor_{i}({delegateType} handler)");
            sb.AppendLine("    {");
            CallbackDescriptorEmitter.EmitDescriptorBody(sb, handler);
            sb.AppendLine("    }");
            sb.AppendLine();
        }
    }
}
